spring:
  application:
    name: messenger
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: ---
    password: "-"
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: --------------------------------------------------------------------------
  expiration: 3600000