

create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    display_name character varying(20) not null,
    email character varying(255) not null unique,
    login character varying(20) not null unique,
    password_hash character varying(255) not null
);


create table conversations (
    id bigint generated by default as identity primary key,
    type character varying(255) not null,
    visibility character varying(255) not null,
    created_at timestamp not null default current_timestamp,
    title character varying(16) not null,
    updated_at timestamp,
    deleted_at timestamp,
    direct_value character varying(255) unique
);


create table members (
    id bigint generated by default as identity primary key,
    status character varying(255),
    conversation_id bigint not null,
    user_id bigint not null,
    last_read_message_id bigint,

    constraint uq_members_user_conversation
        unique (user_id, conversation_id)
    ,
    constraint fk_members_user_conversation
        foreign key (user_id)
        references users(id)
    ,
    constraint fk_members_conversation
        foreign key (conversation_id)
        references conversations(id)
);


create table messages (
    id bigint generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    deleted_at timestamp,
    text character varying(2048),
    conversation_id bigint NOT NULL,
    sender_member_id bigint NOT NULL,

    constraint fk_messages_conversation
        foreign key (conversation_id)
        references conversations(id),

    constraint fk_messages_sender_member
        foreign key (sender_member_id)
        references members(id)
);

create index idx_message_conversationId_createdAt_id
    on messages(conversation_id, created_at, id);


create table message_deletions (
    id bigint generated by default as identity primary key,
    deleted_at timestamp not null default current_timestamp,
    member_id bigint NOT NULL,
    message_id bigint NOT NULL,

    constraint uq_message_deletions_message_member
        unique (message_id, member_id),

    constraint fk_message_deletions_member
        foreign key (member_id)
        references members(id),

    constraint fk_message_deletions_message
        foreign key (message_id)
        references messages(id)
);


